version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: wms-postgres
    environment:
      POSTGRES_DB: wms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 274136
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wms-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wms_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  wms-app:
    build: .
    container_name: wms-application
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: jdbc:postgresql://postgres:5432/wms
      DB_USERNAME: postgres
      DB_PASSWORD: 274136
    ports:
      - "8080:8080"
    networks:
      - wms-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: wms-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@wms.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - wms-network
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  wms-network:
    driver: bridge